// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentResourcesDirectory.Data;

#nullable disable

namespace StudentResourcesDirectory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentResourcesDirectory.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Databases"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Web Development"
                        });
                });

            modelBuilder.Entity("StudentResourcesDirectory.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comprehensive guide to learn C# programming from scratch.",
                            ResourceType = 0,
                            StudentId = 1,
                            Title = "C# Fundamentals Book",
                            Url = "https://example.com/csharp-fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2026, 1, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Official guide to learn EF Core with examples.",
                            ResourceType = 5,
                            StudentId = 2,
                            Title = "Entity Framework Core Guide",
                            Url = "https://example.com/ef-core-guide"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2026, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Step-by-step video tutorials for MVC in ASP.NET.",
                            ResourceType = 2,
                            StudentId = 3,
                            Title = "ASP.NET MVC Video Series",
                            Url = "https://youtube.com/aspnet-mvc"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2026, 1, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beginner-friendly introduction to SQL queries and concepts.",
                            ResourceType = 3,
                            StudentId = 4,
                            Title = "SQL Basics Article",
                            Url = "https://example.com/sql-basics"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2026, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lecture notes covering linear algebra essentials.",
                            ResourceType = 0,
                            StudentId = 5,
                            Title = "Linear Algebra Notes",
                            Url = "https://example.com/linear-algebra"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2026, 1, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quick video tutorials to learn JavaScript fundamentals.",
                            ResourceType = 2,
                            StudentId = 6,
                            Title = "JavaScript Crash Course",
                            Url = "https://youtube.com/js-crash-course"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2026, 1, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Official documentation to build web apps with Blazor.",
                            ResourceType = 5,
                            StudentId = 7,
                            Title = "Blazor Documentation",
                            Url = "https://docs.microsoft.com/blazor"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2026, 1, 8, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete guide for version control using Git and GitHub.",
                            ResourceType = 3,
                            StudentId = 8,
                            Title = "Git & GitHub Guide",
                            Url = "https://example.com/git-guide"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2026, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Book covering Python basics and data science libraries.",
                            ResourceType = 0,
                            StudentId = 9,
                            Title = "Python for Data Science",
                            Url = "https://example.com/python-ds"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedOn = new DateTime(2026, 1, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn responsive web design with HTML, CSS, and Bootstrap.",
                            ResourceType = 4,
                            StudentId = 10,
                            Title = "Responsive Web Design Tutorial",
                            Url = "https://example.com/responsive-web"
                        });
                });

            modelBuilder.Entity("StudentResourcesDirectory.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan.petrov@uni.bg",
                            FacultyNumber = "CS2023001",
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            RegisteredOn = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.georgieva@uni.bg",
                            FacultyNumber = "CS2022002",
                            FirstName = "Maria",
                            LastName = "Georgieva",
                            RegisteredOn = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Email = "georgi.dimitrov@uni.bg",
                            FacultyNumber = "CS2021003",
                            FirstName = "Georgi",
                            LastName = "Dimitrov",
                            RegisteredOn = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Email = "elena.ivanova@uni.bg",
                            FacultyNumber = "CS2019004",
                            FirstName = "Elena",
                            LastName = "Ivanova",
                            RegisteredOn = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "petar.stoyanov@uni.bg",
                            FacultyNumber = "CS2020005",
                            FirstName = "Petar",
                            LastName = "Stoyanov",
                            RegisteredOn = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Email = "viktoria.koleva@uni.bg",
                            FacultyNumber = "CS2023006",
                            FirstName = "Viktoria",
                            LastName = "Koleva",
                            RegisteredOn = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Email = "dimitar.nikolov@uni.bg",
                            FacultyNumber = "CS2022007",
                            FirstName = "Dimitar",
                            LastName = "Nikolov",
                            RegisteredOn = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Email = "kristina.petrova@uni.bg",
                            FacultyNumber = "CS2021008",
                            FirstName = "Kristina",
                            LastName = "Petrova",
                            RegisteredOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Email = "alexander.ivanov@uni.bg",
                            FacultyNumber = "CS2020009",
                            FirstName = "Alexander",
                            LastName = "Ivanov",
                            RegisteredOn = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Email = "simona.georgieva@uni.bg",
                            FacultyNumber = "CS20190010",
                            FirstName = "Simona",
                            LastName = "Georgieva",
                            RegisteredOn = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentResourcesDirectory.Models.Resource", b =>
                {
                    b.HasOne("StudentResourcesDirectory.Models.Category", "Category")
                        .WithMany("Resources")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentResourcesDirectory.Models.Student", "Student")
                        .WithMany("Resources")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentResourcesDirectory.Models.Category", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("StudentResourcesDirectory.Models.Student", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
